version: '3.1'
services:
  app:
    container_name: api
    restart: always
    image: api
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=starwarsdb